import mongoose from 'mongoose'
import Trek from '../models/Trek'
import Batch from '../models/Batch'
import Blog from '../models/Blog'
import Coupon from '../models/Coupon'
import Tour from '../models/Tour'
import dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const MONGODB_URI = process.env.MONGODB_URI || 'YOUR_MONGODB_URI_HERE'

const treks = [
  {
    slug: 'kedarkantha-trek',
    name: 'Kedarkantha Trek',
    region: 'Uttarakhand',
    subRegion: 'Uttarkashi',
    difficulty: 'Easy-Moderate',
    duration: { days: 6, nights: 5 },
    maxAltitude: '12,500 ft',
    startingAltitude: '6,400 ft',
    bestSeason: ['December', 'January', 'February', 'March'],
    startingPrice: 8500,
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    gallery: [
      'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800',
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    ],
    rating: 4.8,
    reviewCount: 342,
    isFeatured: true,
    isActive: true,
    highlights: [
      'Snow-covered trails through pine forests',
      '360° panoramic summit views of Swargarohini, Bandarpunch',
      'Camping under a sky full of stars at Juda Ka Talab',
      'Perfect winter trek for beginners',
    ],
    description: `Kedarkantha is one of India's most popular winter treks, located in the Govind Wildlife Sanctuary in Uttarkashi district. The trail winds through dense pine and oak forests, frozen lakes, and meadows blanketed in snow. The summit at 12,500 ft offers breathtaking 360° views of the Himalayan peaks. This is an ideal trek for beginners wanting their first Himalayan snow experience.`,
    itinerary: [
      { day: 1, title: 'Dehradun to Sankri', description: 'Drive from Dehradun to Sankri (200 km, ~8 hours). Arrive, acclimatize, overnight stay at base camp.', distance: '200 km drive', altitude: '6,400 ft' },
      { day: 2, title: 'Sankri to Juda Ka Talab', description: 'Trek through dense pine forests to the frozen Juda Ka Talab lake. Camp overnight beside the frozen lake.', distance: '4 km', altitude: '9,100 ft' },
      { day: 3, title: 'Juda Ka Talab to Kedarkantha Base', description: 'Short trek to the base camp, offering stunning views of the summit. Rest and acclimatize.', distance: '4 km', altitude: '11,250 ft' },
      { day: 4, title: 'Summit Day — Kedarkantha Peak', description: 'Early 4 AM start for the summit push. Reach the peak (12,500 ft) at sunrise. Descend to Hergaon camp.', distance: '6 km', altitude: '12,500 ft' },
      { day: 5, title: 'Hergaon to Sankri', description: 'Descend through meadows and forests back to Sankri. Celebrate with the group.', distance: '6 km', altitude: '6,400 ft' },
      { day: 6, title: 'Sankri to Dehradun', description: 'Drive back to Dehradun. Tour ends by evening.', distance: '200 km drive', altitude: '2,200 ft' },
    ],
    inclusions: [
      'Accommodation (camps/guesthouses throughout)',
      'All meals from Day 1 dinner to Day 6 breakfast',
      'Experienced trek leader and support staff',
      'Forest permit and camping charges',
      'First aid kit and oxygen cylinder',
      'Transport: Dehradun to Sankri and return',
    ],
    exclusions: [
      'Personal trekking gear (jacket, boots, poles)',
      'Travel insurance',
      'Meals not mentioned in itinerary',
      'Porter charges (available on request at ₹800/day)',
      'Anything not mentioned in inclusions',
    ],
    thingsToBring: [
      'Warm jacket (down/synthetic, -10°C rating)',
      'Trekking boots (ankle support, waterproof)',
      'Woolen cap, gloves, thermal inner',
      'Sunscreen SPF 50+, sunglasses',
      'Personal medicines',
      'Water bottle (2L)',
      'Headlamp with extra batteries',
    ],
    seoMeta: {
      title: 'Kedarkantha Trek 2026 — Complete Guide | Parvatpath',
      description: 'Book Kedarkantha Trek from Dehradun. 6 days, 12,500 ft summit, snow-covered trails. Best winter trek in Uttarakhand. From ₹8,500.',
    },
  },
  {
    slug: 'valley-of-flowers-trek',
    name: 'Valley of Flowers Trek',
    region: 'Uttarakhand',
    subRegion: 'Chamoli',
    difficulty: 'Easy-Moderate',
    duration: { days: 6, nights: 5 },
    maxAltitude: '14,100 ft',
    startingAltitude: '6,200 ft',
    bestSeason: ['July', 'August', 'September'],
    startingPrice: 9500,
    coverImage: 'https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=800',
    gallery: [],
    rating: 4.9,
    reviewCount: 267,
    isFeatured: true,
    isActive: true,
    highlights: [
      'UNESCO World Heritage Site',
      '500+ species of wildflowers in full bloom',
      'Hemkund Sahib Gurudwara at 15,200 ft',
      'Pristine alpine meadows and glacial streams',
    ],
    description: `The Valley of Flowers is a UNESCO World Heritage Site in Chamoli district, bursting with over 500 species of wildflowers from July to September. The valley floor at 11,500–12,500 ft is carpeted with Brahmakamal, Blue Poppy, and countless alpine blooms. Combined with a visit to Hemkund Sahib, this is one of the most spiritually and naturally rewarding treks in India.`,
    itinerary: [
      { day: 1, title: 'Rishikesh/Haridwar to Govindghat', description: 'Drive to Govindghat (270 km). Overnight stay.', distance: '270 km drive', altitude: '6,200 ft' },
      { day: 2, title: 'Govindghat to Ghangaria', description: 'Trek 13 km to Ghangaria, the base village for Valley of Flowers and Hemkund Sahib.', distance: '13 km', altitude: '10,200 ft' },
      { day: 3, title: 'Ghangaria to Valley of Flowers', description: 'Day trek into the valley. Explore the meadows, streams, and wildflowers. Return to Ghangaria.', distance: '8 km', altitude: '12,500 ft' },
      { day: 4, title: 'Ghangaria to Hemkund Sahib', description: 'Trek to the sacred Hemkund Sahib lake at 15,200 ft. Return to Ghangaria.', distance: '12 km', altitude: '15,200 ft' },
      { day: 5, title: 'Ghangaria to Govindghat', description: 'Descend back to Govindghat. Overnight stay.', distance: '13 km', altitude: '6,200 ft' },
      { day: 6, title: 'Govindghat to Rishikesh', description: 'Drive back to Rishikesh. Trek ends.', distance: '270 km drive', altitude: '1,100 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Forest permits', 'Transport Rishikesh-Govindghat-Rishikesh'],
    exclusions: ['Personal gear', 'Travel insurance', 'Porter charges', 'Meals not mentioned'],
    thingsToBring: ['Rain jacket/poncho', 'Trekking boots', 'Warm layers', 'Sunscreen', 'Water bottle', 'Camera'],
    seoMeta: {
      title: 'Valley of Flowers Trek 2026 — UNESCO Heritage | Parvatpath',
      description: 'Book Valley of Flowers Trek from Rishikesh. UNESCO World Heritage Site. 6 days, 500+ wildflower species. Monsoon season special. From ₹9,500.',
    },
  },
  {
    slug: 'har-ki-dun-trek',
    name: 'Har Ki Dun Trek',
    region: 'Uttarakhand',
    subRegion: 'Uttarkashi',
    difficulty: 'Moderate',
    duration: { days: 7, nights: 6 },
    maxAltitude: '11,700 ft',
    startingAltitude: '5,900 ft',
    bestSeason: ['April', 'May', 'June', 'September', 'October'],
    startingPrice: 10500,
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    gallery: [],
    rating: 4.7,
    reviewCount: 189,
    isFeatured: true,
    isActive: true,
    highlights: ['Mythological Mahabharata connection', 'Cradle-shaped valley', 'Ancient Osla village', 'Views of Swargarohini peak'],
    description: `Har Ki Dun, meaning "Valley of Gods", is a cradle-shaped hanging valley in the Govind Wildlife Sanctuary. Believed to be the route taken by the Pandavas in the Mahabharata, this valley offers stunning views of Swargarohini, Bandarpunch, and Black Peak. The trek passes through ancient villages like Osla, which still follows centuries-old traditions.`,
    itinerary: [
      { day: 1, title: 'Dehradun to Sankri', description: 'Drive to Sankri. Overnight stay.', distance: '200 km drive', altitude: '6,400 ft' },
      { day: 2, title: 'Sankri to Taluka to Osla', description: 'Drive to Taluka, then trek through the Supin river valley to ancient Osla village.', distance: '12 km trek', altitude: '7,600 ft' },
      { day: 3, title: 'Osla to Har Ki Dun', description: 'Trek through rhododendron forests and alpine meadows to the valley floor.', distance: '11 km', altitude: '11,700 ft' },
      { day: 4, title: 'Har Ki Dun — Exploration Day', description: 'Explore the valley, attempt day hike toward Swargarohini base.', distance: '6-8 km', altitude: '12,500 ft' },
      { day: 5, title: 'Har Ki Dun to Osla', description: 'Begin descent back through the valley.', distance: '11 km', altitude: '7,600 ft' },
      { day: 6, title: 'Osla to Sankri', description: 'Trek back to Sankri through Taluka.', distance: '12 km', altitude: '6,400 ft' },
      { day: 7, title: 'Sankri to Dehradun', description: 'Drive back to Dehradun.', distance: '200 km drive', altitude: '2,200 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Forest permits', 'Transport'],
    exclusions: ['Personal gear', 'Travel insurance', 'Porter charges'],
    thingsToBring: ['Trekking boots', 'Warm layers', 'Rain jacket', 'Sunscreen', 'Water bottle', 'Headlamp'],
    seoMeta: {
      title: 'Har Ki Dun Trek 2026 — Valley of Gods | Parvatpath',
      description: 'Book Har Ki Dun Trek from Dehradun. 7 days through the mythological Valley of Gods. Views of Swargarohini. From ₹10,500.',
    },
  },
  {
    slug: 'brahmatal-trek',
    name: 'Brahmatal Trek',
    region: 'Uttarakhand',
    subRegion: 'Chamoli',
    difficulty: 'Moderate',
    duration: { days: 6, nights: 5 },
    maxAltitude: '12,250 ft',
    startingAltitude: '7,700 ft',
    bestSeason: ['December', 'January', 'February', 'March'],
    startingPrice: 9000,
    coverImage: 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800',
    gallery: [],
    rating: 4.8,
    reviewCount: 156,
    isFeatured: true,
    isActive: true,
    highlights: ['Frozen Brahmatal lake', 'Views of Trishul and Nanda Ghunti', 'Snow-laden oak and rhododendron forests', 'Lesser-crowded winter trek'],
    description: `Brahmatal is a hidden gem of Uttarakhand winter trekking. Unlike the popular Kedarkantha, Brahmatal sees fewer crowds while offering equally stunning views of Trishul (23,360 ft) and Nanda Ghunti. The frozen Brahmatal lake and the snow-covered trail through oak forests make this one of the most scenic winter treks in Garhwal.`,
    itinerary: [
      { day: 1, title: 'Kathgodam/Rishikesh to Lohajung', description: 'Drive to Lohajung, the base camp for Brahmatal.', distance: '240 km drive', altitude: '7,700 ft' },
      { day: 2, title: 'Lohajung to Bekaltal', description: 'Trek through dense oak forests to Bekaltal lake, frozen in winter.', distance: '6 km', altitude: '8,900 ft' },
      { day: 3, title: 'Bekaltal to Brahmatal', description: 'Trek to Brahmatal campsite through snow-covered meadows.', distance: '6 km', altitude: '10,400 ft' },
      { day: 4, title: 'Brahmatal Summit Push', description: 'Early morning summit attempt (12,250 ft). Stunning panoramic views. Return to camp.', distance: '8 km', altitude: '12,250 ft' },
      { day: 5, title: 'Brahmatal to Lohajung', description: 'Descend back through the forests to Lohajung.', distance: '10 km', altitude: '7,700 ft' },
      { day: 6, title: 'Lohajung to Kathgodam/Rishikesh', description: 'Drive back. Trek concludes.', distance: '240 km drive', altitude: '900 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Forest permits', 'Transport'],
    exclusions: ['Personal gear', 'Travel insurance', 'Porter charges'],
    thingsToBring: ['Heavy down jacket', 'Waterproof boots', 'Gaiters', 'Trekking poles', 'Thermal innerwear'],
    seoMeta: {
      title: 'Brahmatal Trek 2026 — Winter Snow Trek | Parvatpath',
      description: 'Book Brahmatal Trek. 6 days winter trek in Chamoli, Uttarakhand. Frozen lake, Trishul views. Less crowded. From ₹9,000.',
    },
  },
  {
    slug: 'chopta-tungnath-chandrashila',
    name: 'Chopta Tungnath Chandrashila',
    region: 'Uttarakhand',
    subRegion: 'Rudraprayag',
    difficulty: 'Easy-Moderate',
    duration: { days: 4, nights: 3 },
    maxAltitude: '13,123 ft',
    startingAltitude: '8,500 ft',
    bestSeason: ['November', 'December', 'January', 'February', 'March', 'April', 'May'],
    startingPrice: 6500,
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    gallery: [],
    rating: 4.9,
    reviewCount: 412,
    isFeatured: true,
    isActive: true,
    highlights: ['Highest Shiva temple in the world (Tungnath)', 'Chandrashila summit at 13,123 ft', 'Mini Switzerland of Uttarakhand', 'Stunning Kedarnath, Nanda Devi, Trishul views'],
    description: `Chopta is called the "Mini Switzerland of Uttarakhand" — a rolling meadow at 8,500 ft surrounded by dense rhododendron forests. The short but rewarding trek leads to Tungnath (12,073 ft), the world's highest Shiva temple, and Chandrashila peak (13,123 ft) with panoramic views of Kedarnath, Badrinath, Nanda Devi, and Trishul.`,
    itinerary: [
      { day: 1, title: 'Rishikesh/Haridwar to Chopta', description: 'Drive via Devprayag, Rudraprayag to Chopta (210 km). Overnight stay.', distance: '210 km drive', altitude: '8,500 ft' },
      { day: 2, title: 'Chopta to Tungnath to Chandrashila', description: 'Trek 3.5 km to Tungnath temple, then 1.5 km more to Chandrashila summit. Descend back to Chopta.', distance: '10 km', altitude: '13,123 ft' },
      { day: 3, title: 'Chopta — Explore Deoria Tal', description: 'Optional day hike to Deoria Tal (reflection lake) 3 km from Sari village. Back to Chopta.', distance: '8 km', altitude: '7,800 ft' },
      { day: 4, title: 'Chopta to Rishikesh', description: 'Drive back to Rishikesh. Trek concludes.', distance: '210 km drive', altitude: '1,100 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Transport', 'Forest permits'],
    exclusions: ['Personal gear', 'Travel insurance', 'Temple entry fees'],
    thingsToBring: ['Warm jacket', 'Trekking shoes', 'Woolen cap and gloves', 'Sunscreen', 'Water bottle'],
    seoMeta: {
      title: 'Chopta Tungnath Chandrashila Trek 2026 | Parvatpath',
      description: 'Book Chopta Tungnath Chandrashila Trek. 4 days, world\'s highest Shiva temple, 13,123 ft summit. Mini Switzerland of Uttarakhand. From ₹6,500.',
    },
  },
  {
    slug: 'roopkund-trek',
    name: 'Roopkund Trek',
    region: 'Uttarakhand',
    subRegion: 'Chamoli',
    difficulty: 'Difficult',
    duration: { days: 8, nights: 7 },
    maxAltitude: '15,750 ft',
    startingAltitude: '7,700 ft',
    bestSeason: ['May', 'June', 'September'],
    startingPrice: 14500,
    coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
    gallery: [],
    rating: 4.7,
    reviewCount: 198,
    isFeatured: false,
    isActive: true,
    highlights: ['The mysterious Skeleton Lake at 15,750 ft', 'Views of Trishul and Nanda Ghunti', 'Diverse terrain: forests, meadows, glaciers', 'One of India\'s most iconic treks'],
    description: `Roopkund is India's most mysterious trek — a glacial lake at 15,750 ft littered with ancient human skeletons dating back to the 9th century. The trek passes through Bedni Bugyal (one of India's most beautiful meadows), the Kalu Vinayak temple, and a dramatic ridge walk to the skeleton lake. This is a challenging, high-altitude trek for experienced trekkers.`,
    itinerary: [
      { day: 1, title: 'Kathgodam to Lohajung', description: 'Drive to base camp at Lohajung.', distance: '240 km', altitude: '7,700 ft' },
      { day: 2, title: 'Lohajung to Didna', description: 'Trek through terraced fields and oak forests to Didna village.', distance: '9 km', altitude: '8,600 ft' },
      { day: 3, title: 'Didna to Ali Bugyal', description: 'Enter the stunning Ali Bugyal meadow — one of the largest high-altitude meadows in India.', distance: '7 km', altitude: '11,900 ft' },
      { day: 4, title: 'Ali Bugyal to Bedni Bugyal', description: 'Trek through the vast meadows of Bedni Bugyal with views of Trishul.', distance: '5 km', altitude: '11,900 ft' },
      { day: 5, title: 'Bedni to Bhagwabasa via Kalu Vinayak', description: 'Cross the rocky terrain and reach the last campsite before the lake.', distance: '10 km', altitude: '14,100 ft' },
      { day: 6, title: 'Summit Day — Roopkund Lake', description: 'Early morning push to Roopkund lake (15,750 ft). Return to Bedni.', distance: '8 km', altitude: '15,750 ft' },
      { day: 7, title: 'Bedni to Lohajung', description: 'Long descent back through Didna to Lohajung.', distance: '20 km', altitude: '7,700 ft' },
      { day: 8, title: 'Lohajung to Kathgodam', description: 'Drive back. Trek ends.', distance: '240 km', altitude: '900 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Forest permits', 'Transport'],
    exclusions: ['Personal gear', 'Travel insurance', 'Porter charges (₹1,200/day)'],
    thingsToBring: ['Heavy down jacket', 'Crampon-compatible boots', 'Trekking poles', 'Gaiters', 'Headlamp', 'High SPF sunscreen'],
    seoMeta: {
      title: 'Roopkund Trek 2026 — Skeleton Lake Trek | Parvatpath',
      description: 'Book Roopkund Skeleton Lake Trek. 8 days, 15,750 ft. India\'s most mysterious trek through Bedni Bugyal. From ₹14,500.',
    },
  },
  {
    slug: 'nag-tibba-trek',
    name: 'Nag Tibba Trek',
    region: 'Uttarakhand',
    subRegion: 'Tehri',
    difficulty: 'Easy',
    duration: { days: 2, nights: 1 },
    maxAltitude: '9,915 ft',
    startingAltitude: '6,900 ft',
    bestSeason: ['November', 'December', 'January', 'February', 'March', 'April'],
    startingPrice: 2800,
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
    gallery: [],
    rating: 4.6,
    reviewCount: 523,
    isFeatured: false,
    isActive: true,
    highlights: ['Highest peak in lower Himalayas of Garhwal', 'Perfect weekend trek from Delhi/Dehradun', 'Snow in winter months', 'Panoramic Himalayan views'],
    description: `Nag Tibba is the perfect weekend escape from Delhi and Dehradun. At 9,915 ft, it's the highest peak in the lower Himalayan ranges of Garhwal and can be done in just 2 days. The trail goes through dense oak and rhododendron forests with stunning views of Kedarnath, Bandarpunch, and Swargarohini from the top.`,
    itinerary: [
      { day: 1, title: 'Dehradun to Nag Tibba Base — Summit', description: 'Drive to Pantwari (base village). Trek 6 km to summit (9,915 ft). Descend to campsite. Overnight camp under stars.', distance: '7 km trek', altitude: '9,915 ft' },
      { day: 2, title: 'Camp to Pantwari to Dehradun', description: 'Morning views, breakfast, descend to Pantwari. Drive back to Dehradun.', distance: '7 km trek', altitude: '6,900 ft' },
    ],
    inclusions: ['Tent camping', 'All meals', 'Trek leader', 'Transport Dehradun-Pantwari-Dehradun'],
    exclusions: ['Personal sleeping bag (available on rent)', 'Travel insurance'],
    thingsToBring: ['Warm jacket', 'Trekking shoes', 'Headlamp', 'Water bottle', 'Personal medicines'],
    seoMeta: {
      title: 'Nag Tibba Trek — Weekend Trek from Dehradun | Parvatpath',
      description: 'Book Nag Tibba weekend trek. 2 days from Dehradun. Best beginner trek in Uttarakhand. Snow in winter. From ₹2,800.',
    },
  },
  {
    slug: 'kedarnath-trek',
    name: 'Kedarnath Trek',
    region: 'Uttarakhand',
    subRegion: 'Rudraprayag',
    difficulty: 'Moderate',
    duration: { days: 4, nights: 3 },
    maxAltitude: '11,755 ft',
    startingAltitude: '6,578 ft',
    bestSeason: ['May', 'June', 'September', 'October'],
    startingPrice: 7500,
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
    gallery: [],
    rating: 4.9,
    reviewCount: 687,
    isFeatured: true,
    isActive: true,
    highlights: ['One of the 12 Jyotirlinga shrines', '16 km trek to the sacred temple', 'Stunning Mandakini river valley', 'Spiritual + trekking experience combined'],
    description: `The Kedarnath Trek is one of India's most sacred pilgrimages combined with a magnificent Himalayan trek. The 16 km trail from Gaurikund to Kedarnath temple (11,755 ft) winds along the Mandakini river through alpine meadows. The ancient stone temple, surrounded by snow-capped peaks, is one of the most awe-inspiring sights in the Himalayas.`,
    itinerary: [
      { day: 1, title: 'Haridwar/Rishikesh to Sonprayag', description: 'Drive to Sonprayag via Rudraprayag (210 km). Overnight stay.', distance: '210 km', altitude: '5,900 ft' },
      { day: 2, title: 'Sonprayag to Kedarnath', description: 'Drive to Gaurikund, then 16 km trek to Kedarnath temple. Evening aarti at the temple.', distance: '16 km trek', altitude: '11,755 ft' },
      { day: 3, title: 'Kedarnath — Temple Darshan', description: 'Early morning abhishek, explore Bhairav temple, Gandhi Sarovar. Afternoon at leisure.', distance: '4-6 km', altitude: '11,755 ft' },
      { day: 4, title: 'Kedarnath to Gaurikund to Haridwar', description: 'Descend 16 km to Gaurikund. Drive back to Haridwar. Trek ends.', distance: '16 km trek', altitude: '1,100 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Transport', 'Darshan assistance'],
    exclusions: ['Personal gear', 'Pony/helicopter charges', 'Donation/prasad at temple', 'Travel insurance'],
    thingsToBring: ['Warm layers', 'Rain jacket', 'Comfortable trekking shoes', 'Walking stick', 'Personal medicines'],
    seoMeta: {
      title: 'Kedarnath Trek 2026 — Pilgrimage Package | Parvatpath',
      description: 'Book Kedarnath Trek package from Haridwar. 4 days pilgrimage + trek to the sacred Jyotirlinga. From ₹7,500.',
    },
  },
  {
    slug: 'dayara-bugyal-trek',
    name: 'Dayara Bugyal Trek',
    region: 'Uttarakhand',
    subRegion: 'Uttarkashi',
    difficulty: 'Easy-Moderate',
    duration: { days: 5, nights: 4 },
    maxAltitude: '12,100 ft',
    startingAltitude: '7,900 ft',
    bestSeason: ['January', 'February', 'March', 'June', 'July', 'August', 'September', 'October'],
    startingPrice: 8000,
    coverImage: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800',
    gallery: [],
    rating: 4.7,
    reviewCount: 134,
    isFeatured: false,
    isActive: true,
    highlights: ['One of the largest high-altitude meadows in India', 'Stunning views of Draupadi Ka Danda and Bandarpunch', 'Skiing destination in winter', 'Year-round trekking possibility'],
    description: `Dayara Bugyal is one of India's most stunning high-altitude meadows, stretching across a vast plateau at 10,000–12,000 ft in Uttarkashi. In winter it transforms into a ski resort; in summer the meadow is covered with wildflowers. The 360° panorama includes Draupadi Ka Danda, Bandarpunch, Srikanth, and Gangotri peaks.`,
    itinerary: [
      { day: 1, title: 'Dehradun to Barsu', description: 'Drive to Barsu village via Uttarkashi (170 km). Base camp.', distance: '170 km', altitude: '7,900 ft' },
      { day: 2, title: 'Barsu to Dayara Bugyal', description: 'Trek through oak and rhododendron forests to the vast Dayara meadow.', distance: '6 km', altitude: '11,000 ft' },
      { day: 3, title: 'Dayara Bugyal Exploration', description: 'Explore the full meadow, trek to Bakaria Top (12,100 ft) for panoramic views.', distance: '8 km', altitude: '12,100 ft' },
      { day: 4, title: 'Dayara to Barsu', description: 'Descend back through the forest to Barsu.', distance: '6 km', altitude: '7,900 ft' },
      { day: 5, title: 'Barsu to Dehradun', description: 'Drive back to Dehradun.', distance: '170 km', altitude: '2,200 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Transport', 'Forest permits'],
    exclusions: ['Personal gear', 'Travel insurance', 'Porter charges'],
    thingsToBring: ['Warm jacket', 'Trekking boots', 'Sunscreen', 'Sunglasses', 'Water bottle'],
    seoMeta: {
      title: 'Dayara Bugyal Trek 2026 — Alpine Meadow Trek | Parvatpath',
      description: 'Book Dayara Bugyal Trek from Dehradun. 5 days in Uttarakhand\'s most beautiful meadow. Skiing in winter. From ₹8,000.',
    },
  },
  {
    slug: 'dodital-trek',
    name: 'Dodital Trek',
    region: 'Uttarakhand',
    subRegion: 'Uttarkashi',
    difficulty: 'Moderate',
    duration: { days: 5, nights: 4 },
    maxAltitude: '13,000 ft',
    startingAltitude: '5,500 ft',
    bestSeason: ['April', 'May', 'June', 'September', 'October'],
    startingPrice: 9500,
    coverImage: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800',
    gallery: [],
    rating: 4.6,
    reviewCount: 89,
    isFeatured: false,
    isActive: true,
    highlights: ['Sacred Dodital lake, birthplace of Lord Ganesha', 'Dense Himalayan forests', 'Himalayan trout fishing in the lake', 'Optional extension to Darwa Top'],
    description: `Dodital is a pristine freshwater lake at 10,400 ft in Uttarkashi, believed to be the birthplace of Lord Ganesha. The trail winds through dense forests of oak, rhododendron, and pine. The serene blue lake surrounded by snow-capped peaks is one of Uttarakhand's most peaceful destinations. Himalayan brown trout can be spotted in the crystal-clear waters.`,
    itinerary: [
      { day: 1, title: 'Dehradun to Sangamchatti', description: 'Drive via Uttarkashi to Sangamchatti base village.', distance: '185 km', altitude: '5,500 ft' },
      { day: 2, title: 'Sangamchatti to Agoda', description: 'Trek through forest trail to Agoda campsite.', distance: '9 km', altitude: '8,300 ft' },
      { day: 3, title: 'Agoda to Dodital', description: 'Trek to the sacred Dodital lake. Afternoon at the lake.', distance: '6 km', altitude: '10,400 ft' },
      { day: 4, title: 'Dodital to Darwa Top (Optional) + Return to Agoda', description: 'Optional 5 km hike to Darwa Top (13,000 ft) for Himalayan views. Descend to Agoda.', distance: '10-15 km', altitude: '13,000 ft' },
      { day: 5, title: 'Agoda to Sangamchatti to Dehradun', description: 'Descend to base, drive back to Dehradun.', distance: '9 km trek + 185 km drive', altitude: '2,200 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Transport', 'Forest permits'],
    exclusions: ['Personal gear', 'Fishing permit (₹500/day)', 'Travel insurance'],
    thingsToBring: ['Trekking boots', 'Warm jacket', 'Rain jacket', 'Water bottle', 'Headlamp'],
    seoMeta: {
      title: 'Dodital Trek 2026 — Sacred Lake Trek Uttarakhand | Parvatpath',
      description: 'Book Dodital Trek from Dehradun. 5 days to the sacred birthplace of Lord Ganesha. Himalayan trout lake. From ₹9,500.',
    },
  },
  {
    slug: 'kuari-pass-trek',
    name: 'Kuari Pass Trek',
    region: 'Uttarakhand',
    subRegion: 'Chamoli',
    difficulty: 'Moderate',
    duration: { days: 6, nights: 5 },
    maxAltitude: '12,516 ft',
    startingAltitude: '6,200 ft',
    bestSeason: ['November', 'December', 'January', 'February', 'March', 'April'],
    startingPrice: 11000,
    coverImage: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
    gallery: [],
    rating: 4.8,
    reviewCount: 167,
    isFeatured: false,
    isActive: true,
    highlights: ['Lord Curzon Trail (historic colonial-era route)', 'Stunning views of Nanda Devi, Dronagiri, Kamet', 'Khullara meadow camping', 'Winter snow + summer flower bloom'],
    description: `Kuari Pass, also called Lord Curzon's Trail after the British Viceroy who trekked it in 1905, offers some of the finest Himalayan views in Garhwal. The pass at 12,516 ft opens up a breathtaking panorama of Nanda Devi (India's 2nd highest peak), Dronagiri, Kamet, and Hathi Ghoda. The trail through Khullara meadow is magical in both winter snow and summer wildflower season.`,
    itinerary: [
      { day: 1, title: 'Haridwar to Joshimath', description: 'Drive via Devprayag, Rudraprayag to Joshimath (290 km).', distance: '290 km', altitude: '6,200 ft' },
      { day: 2, title: 'Joshimath to Dhak to Gulling', description: 'Drive to Dhak village, trek through oak forests to Gulling camp.', distance: '7 km trek', altitude: '8,800 ft' },
      { day: 3, title: 'Gulling to Khullara', description: 'Trek through beautiful Khullara meadow with Himalayan views.', distance: '8 km', altitude: '11,500 ft' },
      { day: 4, title: 'Khullara to Kuari Pass to Chitrakantha', description: 'Trek to Kuari Pass summit (12,516 ft). 180° Himalayan panorama. Descend to Chitrakantha.', distance: '10 km', altitude: '12,516 ft' },
      { day: 5, title: 'Chitrakantha to Tapovan', description: 'Descend through forests to Tapovan.', distance: '8 km', altitude: '7,900 ft' },
      { day: 6, title: 'Tapovan to Joshimath to Haridwar', description: 'Drive back via Joshimath to Haridwar.', distance: '290 km', altitude: '1,100 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Transport', 'Forest permits'],
    exclusions: ['Personal gear', 'Travel insurance', 'Porter charges'],
    thingsToBring: ['Down jacket', 'Waterproof trekking boots', 'Sunscreen', 'Trekking poles', 'Water bottle'],
    seoMeta: {
      title: 'Kuari Pass Trek 2026 — Lord Curzon Trail | Parvatpath',
      description: 'Book Kuari Pass Trek (Lord Curzon Trail). 6 days in Chamoli, Uttarakhand. Nanda Devi views. From ₹11,000.',
    },
  },
  {
    slug: 'pangarchulla-peak',
    name: 'Pangarchulla Peak Trek',
    region: 'Uttarakhand',
    subRegion: 'Chamoli',
    difficulty: 'Difficult',
    duration: { days: 7, nights: 6 },
    maxAltitude: '15,069 ft',
    startingAltitude: '6,200 ft',
    bestSeason: ['April', 'May', 'October', 'November'],
    startingPrice: 16500,
    coverImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800',
    gallery: [],
    rating: 4.8,
    reviewCount: 92,
    isFeatured: false,
    isActive: true,
    highlights: ['Technical peak summit at 15,069 ft', '360° views: Nanda Devi, Dronagiri, Chaukhamba', 'Rope, ice axe, crampons experience', 'Combine with Kuari Pass'],
    description: `Pangarchulla is a challenging technical peak in Chamoli district, rising to 15,069 ft. Unlike most Himalayan treks, Pangarchulla requires the use of crampons, ice axe, and rope on the final summit push — making it a true mountaineering experience. The 360° summit views include Nanda Devi, Dronagiri, Nilkantha, Mana, and Kamet peaks.`,
    itinerary: [
      { day: 1, title: 'Haridwar to Joshimath', description: 'Drive to Joshimath base camp.', distance: '290 km', altitude: '6,200 ft' },
      { day: 2, title: 'Joshimath to Dhak to Gulling', description: 'Trek to Gulling camp through oak forests.', distance: '7 km', altitude: '8,800 ft' },
      { day: 3, title: 'Gulling to Khullara', description: 'Trek through Khullara meadow.', distance: '8 km', altitude: '11,500 ft' },
      { day: 4, title: 'Khullara to Pangarchulla Base', description: 'Trek to the base camp below the summit.', distance: '5 km', altitude: '13,500 ft' },
      { day: 5, title: 'Summit Day — Pangarchulla Peak', description: 'Early 3 AM push. Crampon, ice axe section near summit. 360° views. Return to base.', distance: '6 km', altitude: '15,069 ft' },
      { day: 6, title: 'Base to Tapovan', description: 'Descend through forests to Tapovan.', distance: '12 km', altitude: '7,900 ft' },
      { day: 7, title: 'Tapovan to Joshimath to Haridwar', description: 'Drive back. Trek concludes.', distance: '290 km', altitude: '1,100 ft' },
    ],
    inclusions: ['Accommodation throughout', 'All meals', 'Trek leader', 'Crampon/ice axe on rent', 'Ropes and safety equipment', 'Transport', 'Forest permits'],
    exclusions: ['Personal high-altitude gear', 'Travel insurance (mandatory for this trek)', 'Porter charges'],
    thingsToBring: ['8000m rated down jacket', 'Double-layer trekking boots', 'Gaiters', 'Sunglasses (glacier)', 'High SPF sunscreen', 'Personal medicines'],
    seoMeta: {
      title: 'Pangarchulla Peak Trek 2026 — 15,069 ft | Parvatpath',
      description: 'Book Pangarchulla Peak Trek. 7 days technical peak in Chamoli. Crampons, ice axe, 15,069 ft summit. Nanda Devi views. From ₹16,500.',
    },
  },
]

// Batch dates for each trek (2 future batches each)
const getBatches = (trekId: mongoose.Types.ObjectId, basePrice: number) => [
  {
    trekId,
    startDate: new Date('2026-10-15'),
    endDate: new Date('2026-10-21'),
    price: basePrice,
    totalSeats: 20,
    bookedSeats: Math.floor(Math.random() * 15),
    isActive: true,
  },
  {
    trekId,
    startDate: new Date('2026-11-05'),
    endDate: new Date('2026-11-11'),
    price: Math.round(basePrice * 1.05),
    totalSeats: 20,
    bookedSeats: Math.floor(Math.random() * 10),
    isActive: true,
  },
  {
    trekId,
    startDate: new Date('2026-12-10'),
    endDate: new Date('2026-12-16'),
    price: Math.round(basePrice * 1.1),
    totalSeats: 20,
    bookedSeats: Math.floor(Math.random() * 5),
    isActive: true,
  },
]

const blogs = [
  {
    slug: 'kedarkantha-trek-complete-guide-2026',
    title: 'Kedarkantha Trek: Complete Guide for 2026',
    excerpt: 'Everything you need to know about Kedarkantha — the best winter snow trek in Uttarakhand. Itinerary, difficulty, cost, and what to pack.',
    content: '<h2>Why Kedarkantha?</h2><p>Kedarkantha remains India\'s most popular winter snow trek for good reason...</p>',
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    category: 'Destinations',
    author: 'Parvatpath Team',
    readTime: 8,
    isPublished: true,
    publishedAt: new Date('2026-01-15'),
  },
  {
    slug: 'what-to-pack-himalayan-trek',
    title: 'What to Pack for a Himalayan Trek: The Ultimate Checklist',
    excerpt: 'The definitive packing list for Himalayan treks. What you absolutely need, what to leave at home, and gear rental options.',
    content: '<h2>The Essentials</h2><p>Packing right can make or break your Himalayan trek experience...</p>',
    coverImage: 'https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800',
    category: 'Gear',
    author: 'Parvatpath Team',
    readTime: 10,
    isPublished: true,
    publishedAt: new Date('2026-02-01'),
  },
  {
    slug: 'best-treks-uttarakhand-beginners',
    title: 'Best Treks in Uttarakhand for Beginners (2026)',
    excerpt: 'New to trekking? These 5 Uttarakhand treks are perfect for first-timers — accessible, stunning, and safe with the right guide.',
    content: '<h2>Starting Your Trekking Journey</h2><p>Uttarakhand is the perfect destination for beginner trekkers...</p>',
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
    category: 'Trek Tips',
    author: 'Parvatpath Team',
    readTime: 7,
    isPublished: true,
    publishedAt: new Date('2026-02-20'),
  },
  {
    slug: 'altitude-sickness-prevention-cure',
    title: 'Altitude Sickness: How to Prevent and Treat AMS in the Himalayas',
    excerpt: 'Acute Mountain Sickness (AMS) is real and can ruin your trek. Here\'s how to recognize symptoms, prevent it, and treat it effectively.',
    content: '<h2>Understanding AMS</h2><p>Altitude sickness happens when you ascend too quickly...</p>',
    coverImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
    category: 'Safety',
    author: 'Parvatpath Team',
    readTime: 6,
    isPublished: true,
    publishedAt: new Date('2026-03-05'),
  },
]

const tours = [
  {
    slug: 'valley-of-flowers-tour',
    name: 'Valley of Flowers Leisure Tour',
    type: 'Leisure',
    duration: { days: 5, nights: 4 },
    startingPrice: 12000,
    coverImage: 'https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=800',
    description: 'A relaxed version of the Valley of Flowers trek with better accommodation options.',
    itinerary: [
      { day: 1, title: 'Arrival in Rishikesh', description: 'Arrive in Rishikesh and relax.' },
      { day: 2, title: 'Drive to Govindghat', description: 'Scenic drive up the mountains.' },
    ],
    inclusions: ['Hotels', 'Meals', 'Transport'],
    exclusions: ['Flights', 'Personal expenses'],
    isActive: true,
  },
  {
    slug: 'kedarnath-badrinath-do-dham',
    name: 'Kedarnath Badrinath Do Dham Yatra',
    type: 'Char Dham',
    duration: { days: 7, nights: 6 },
    startingPrice: 18500,
    coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
    description: 'A spiritual journey to two of the most sacred shrines in Uttarakhand.',
    itinerary: [
      { day: 1, title: 'Haridwar to Guptkashi', description: 'Drive to Guptkashi.' },
      { day: 2, title: 'Guptkashi to Kedarnath', description: 'Trek or helicopter to Kedarnath.' },
    ],
    inclusions: ['Hotels', 'Meals', 'Transport', 'Darshan assistance'],
    exclusions: ['Helicopter tickets', 'Personal expenses'],
    isActive: true,
  }
]

async function seed() {
  try {
    console.log('Connecting to MongoDB...')
    await mongoose.connect(MONGODB_URI, { dbName: 'parvatpath' })
    console.log('Connected.')

    console.log('Clearing existing data...')
    await Trek.deleteMany({})
    await Batch.deleteMany({})
    await Blog.deleteMany({})
    await Coupon.deleteMany({})
    await Tour.deleteMany({})

    console.log('Seeding Treks and Batches...')
    for (const trekData of treks) {
      const trek = await Trek.create(trekData)
      const batchesData = getBatches(trek._id as mongoose.Types.ObjectId, trek.startingPrice)
      await Batch.insertMany(batchesData)
    }

    console.log('Seeding Blogs...')
    await Blog.insertMany(blogs)

    console.log('Seeding Tours...')
    await Tour.insertMany(tours)

    console.log('Seeding Coupons...')
    await Coupon.create([
      {
        code: 'EARLYBIRD',
        discountType: 'percent',
        value: 10,
        minOrderAmount: 5000,
        maxUses: 100,
        expiry: new Date('2026-12-31'),
      },
      {
        code: 'GROUP5',
        discountType: 'flat',
        value: 2000,
        minOrderAmount: 20000,
        maxUses: 50,
        expiry: new Date('2026-12-31'),
      },
    ])

    console.log('Database seeded successfully!')
    process.exit(0)
  } catch (error) {
    console.error('Error seeding database:', error)
    process.exit(1)
  }
}

seed()
